/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/teacher/ActionButton.vue')['default']
    ActionFeedback: typeof import('./src/components/ui/ActionFeedback.vue')['default']
    AlertPanel: typeof import('./src/components/teacher/AlertPanel.vue')['default']
    AnimatedNumber: typeof import('./src/components/ui/AnimatedNumber.vue')['default']
    AnnouncementEditor: typeof import('./src/components/teacher/AnnouncementEditor.vue')['default']
    AnnouncementHistory: typeof import('./src/components/teacher/AnnouncementHistory.vue')['default']
    AnnouncementStatsModal: typeof import('./src/components/admin/AnnouncementStatsModal.vue')['default']
    BaseButton: typeof import('./src/components/ui/BaseButton.vue')['default']
    BaseCourseCard: typeof import('./src/components/ui/BaseCourseCard.vue')['default']
    BaseEmptyState: typeof import('./src/components/ui/BaseEmptyState.vue')['default']
    BaseInput: typeof import('./src/components/ui/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/ui/BaseModal.vue')['default']
    BaseSectionHeader: typeof import('./src/components/ui/BaseSectionHeader.vue')['default']
    BaseSelect: typeof import('./src/components/ui/BaseSelect.vue')['default']
    BaseToast: typeof import('./src/components/ui/BaseToast.vue')['default']
    BatchActionToolbar: typeof import('./src/components/teacher/BatchActionToolbar.vue')['default']
    ChapterCommentSection: typeof import('./src/components/comments/ChapterCommentSection.vue')['default']
    CommentInput: typeof import('./src/components/comments/CommentInput.vue')['default']
    CommentItem: typeof import('./src/components/comments/CommentItem.vue')['default']
    CommentSortSelector: typeof import('./src/components/comments/CommentSortSelector.vue')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    CourseDistributionChart: typeof import('./src/components/charts/CourseDistributionChart.vue')['default']
    CourseRankingList: typeof import('./src/components/teacher/CourseRankingList.vue')['default']
    DailyGoalProgress: typeof import('./src/components/student/DailyGoalProgress.vue')['default']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    ErrorReportPanel: typeof import('./src/components/teacher/ErrorReportPanel.vue')['default']
    FormField: typeof import('./src/components/ui/FormField.vue')['default']
    GlassCard: typeof import('./src/components/ui/GlassCard.vue')['default']
    GradingWorkbench: typeof import('./src/components/teacher/GradingWorkbench.vue')['default']
    HomeworkQA: typeof import('./src/components/student/HomeworkQA.vue')['default']
    HomeworkQAManagement: typeof import('./src/components/teacher/HomeworkQAManagement.vue')['default']
    InfoPanel: typeof import('./src/components/teacher/InfoPanel.vue')['default']
    KnowledgeMasteryChart: typeof import('./src/components/charts/KnowledgeMasteryChart.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    MobileDrawer: typeof import('./src/components/ui/MobileDrawer.vue')['default']
    NotificationDropdown: typeof import('./src/components/NotificationDropdown.vue')['default']
    OfflineNotice: typeof import('./src/components/OfflineNotice.vue')['default']
    OnlineUsersModal: typeof import('./src/components/admin/OnlineUsersModal.vue')['default']
    QuickActions: typeof import('./src/components/teacher/QuickActions.vue')['default']
    QuizTrendChart: typeof import('./src/components/charts/QuizTrendChart.vue')['default']
    ResponsiveContainer: typeof import('./src/components/ui/ResponsiveContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonCard: typeof import('./src/components/ui/SkeletonCard.vue')['default']
    SkeletonDashboard: typeof import('./src/components/ui/SkeletonDashboard.vue')['default']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader.vue')['default']
    SkeletonTable: typeof import('./src/components/ui/SkeletonTable.vue')['default']
    StatCard: typeof import('./src/components/teacher/StatCard.vue')['default']
    StudentDetailModal: typeof import('./src/components/teacher/StudentDetailModal.vue')['default']
    UrgentHomeworkBanner: typeof import('./src/components/student/UrgentHomeworkBanner.vue')['default']
    UrgentItemsPanel: typeof import('./src/components/teacher/UrgentItemsPanel.vue')['default']
    UserTrendChart: typeof import('./src/components/charts/UserTrendChart.vue')['default']
    WeeklyTrendChart: typeof import('./src/components/charts/WeeklyTrendChart.vue')['default']
  }
}
